version: '3'
services:
  
  nginx:
    build: .
    restart: unless-stopped
    container_name: nginx-rtmp
    tty: true
    ports:
      - "80:80"
      - "1935:1935"
      - "5000:5000"
    networks:
      - app-network
      - app-front
    volumes:
      - webpage
  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mybb
      MYSQL_USER: mybb
      MYSQL_PASSWORD: changeme
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    networks:
      - app-network
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql


  front:
    build:
      context: ./apps/Streaming.WebPage
      build: Dockerfile
    container_name: svelte-front
    ports:
      - "80:80"
      - "1935:1935"
      - "5000:5000"
    networks:
      - app-front
     volumes:
      - webpage

